db:
  username: root
  password: 123456
  ip_port: 0.0.0.0:3306
eth:
  etherscan_api_key: xxxxxx
  scan_request_frequency: 300
  address_generation_quantity: 20
proxy:
  enable: true
  address: http://0.0.0.0:8080
words_list: english

